server:
  port: ${API_GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: false
      routes:
        - id: course-service
          uri: ${COURSE_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/course/**
          filters:
            - StripPrefix=1
        - id: booking-service
          uri: ${BOOKING_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/booking/**
          filters:
            - StripPrefix=1

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Course Service
        url: /course/v3/api-docs
      - name: Booking Service
        url: /booking/v3/api-docs
